source("scripts/bootstrap.R")
bootstrap_renv()
options(repos = c(CRAN = "https://cloud.r-project.org"), timeout = 300)
Sys.setenv(RENV_CONFIG_AUTOLOADER_ENABLED = "FALSE", RENV_CONFIG_CACHE_ENABLED = "FALSE")
lib <- file.path(getwd(), ".work", "dependencies")
dir.create(lib, recursive = TRUE, showWarnings = FALSE)
renv::restore(project = getwd(), lockfile = "renv.lock", library = lib, prompt = FALSE)
